name: flare_maze
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.0
  url_launcher: ^6.3.0

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  color: '#ffffff'
  image: assets/images/logo.png
  android: true
  ios: true
  web: false

  android_12:
    color: '#ffffff'
    icon_background_color: '#ffffff'
    image: assets/images/logo_12.png 